# This deployment and service can be used to test event sources.
# Configure the sink of the event source to be this service
# (i.e. event-display.dogfood.svc.cluster.local).
# The deployment prints out the events received from the source.
# For logs: kubectl logs -l app=event-display -n dogfood -f
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-display
  namespace: dogfood
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: event-display
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: event-display
          image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
---
kind: Service
apiVersion: v1
metadata:
  name: event-display
  namespace: dogfood
spec:
  selector:
    app: event-display
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
