apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-pipeline-with-flux
  namespace: dogfood
spec:
  workspaces:
  - name: source
  params:
  - name: repo-full-name
  - name: revision
  tasks:
  - name: clone
    taskRef:
      name: git-clone # TODO: do we need this if flux will clone the repo?
      bundle: gcr.io/tekton-releases/catalog/upstream/git-clone:0.7
    workspaces:
    - name: output
      workspace: source
    params:
    - name: url
      value: https://github.com/$(params.repo-full-name)
    - name: revision
      value: $(params.revision)
  - name: unit-tests
    taskRef:
      name: pytest
      bundle: gcr.io/tekton-releases/catalog/upstream/pytest:0.1
    workspaces:
    - name: source
      workspace: source
    runAfter:
    - clone