apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: docker-build-pipeline
spec:
  workspaces:
  - name: source-code
  - name: cache
  params:
  - name: image
  - name: registry
  tasks:
  - name: clone
    taskRef:
      resolver: hub
      params:
      - name: name
        value: git-clone
      - name: version
        value: "0.9"
    workspaces:
    - name: output
      workspace: source-code
    params:
    - name: url
      value: https://github.com/lbernick/web-app-demo
  - name: build
    taskRef:
      name: docker-build
    workspaces:
    - name: source
      workspace: source-code
    - name: cache
      workspace: cache
    params:
    - name: image
      value: $(params.image)
    - name: registry
      value: $(params.registry)
    runAfter:
    - clone