apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ci-pipeline
spec:
  workspaces:
  - name: source
  - name: github-app-private-key
  params:
  - name: repo-full-name
  - name: revision
  - name: github-app-id
  - name: app-installation-id
  tasks:
  - name: create-check-runs
    taskRef:
      name: update-github-check-run
    params:
    - name: repo-full-name
      value: $(params.repo-full-name)
    - name: git-sha
      value: $(params.revision)
    - name: status
      value: "in_progress"
    - name: check-run-name
      value: ci
    - name: externalid
      value: $(context.pipelineRun.name)
    - name: github-app-id
      value: $(params.github-app-id)
    - name: app-installation-id
      value: $(params.app-installation-id)
    workspaces:
    - name: github-app-private-key
      workspace: github-app-private-key
  - name: clone
    taskRef:
      resolver: hub
      params:
      - name: name
        value: git-clone
      - name: version
        value: "0.7"
    workspaces:
    - name: output
      workspace: source
    params:
    - name: url
      value: https://github.com/$(params.repo-full-name)
    - name: revision
      value: $(params.revision)
  - name: unit-tests
    taskRef:
      resolver: hub
      params:
      - name: name
        value: pytest
      - name: version
        value: "0.1"
    params:
    - name: SOURCE_PATH
      value: ./src
    workspaces:
    - name: source
      workspace: source
    runAfter:
    - clone
  - name: lint
    taskRef:
      resolver: hub
      params:
      - name: name
        value: black
      - name: version
        value: "0.2"
    params:
    - name: image
      value: docker.io/cytopia/black:latest-py3.7-manifest-linux-amd64@sha256:c15279695a5d7a5114a3b3b613a98ec745e875b07ed39860a7c5bcb8bb6053b8
    workspaces:
    - name: shared-workspace
      workspace: source
    runAfter:
    - clone
  - name: integration-tests
    taskRef:
      name: integration-tests
    params:
    - name: SOURCE_PATH
      value: ./test
    workspaces:
    - name: source
      workspace: source
    runAfter:
    - clone
  finally:
  - name: post-github-status
    taskRef:
      name: update-github-check-run
    params:
    - name: status
      value: completed
    - name: conclusion
      value: $(tasks.unit-tests.status)
    - name: repo-full-name
      value: $(params.repo-full-name)
    - name: git-sha
      value: $(params.revision)
    - name: check-run-name
      value: ci
    - name: externalid
      value: $(context.pipelineRun.name)
    - name: github-app-id
      value: $(params.github-app-id)
    - name: app-installation-id
      value: $(params.app-installation-id)
    workspaces:
    - name: github-app-private-key
      workspace: github-app-private-key
