apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: clone-docker-build-push
spec:
  description: |
    This pipeline clones a git repo, builds a Docker image and
    pushes it to Google Artifact repository.
  workspaces:
  - name: source-code
  params:
  - name: image
  - name: repo-url
  - name: registry
  results:
  - name: image-digest
    value: $(tasks.build-and-push.results.IMAGE_DIGEST)
  tasks:
  - name: fetch-source
    taskRef:
      resolver: hub
      params:
      - name: kind
        value: task
      - name: name
        value: git-clone
      - name: version
        value: "0.7"
    workspaces:
    - name: output
      workspace: source-code
    params:
    - name: url
      value: $(params.repo-url)
  - name: build-and-push
    taskRef:
      name: docker-build
    params:
    - name: image
      value: $(params.image)
    - name: registry
      value: $(params.registry)
    workspaces:
    - name: source
      workspace: source-code
    runAfter:
    - fetch-source