apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: clone-kaniko-build-push-run-
spec:
  pipelineRef:
    name: clone-kaniko-build-push
  params:
  - name: repo-url
    value: https://github.com/lbernick/web-app-demo
  - name: image
    value: us-east1-docker.pkg.dev/leebernick-test/codelab/web-app-demo
  # - name: chat-webhook-url
  #   value: https://chat.googleapis.com/v1/spaces/AAAAGDLkJiM/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=PJjU6o5bxDsarG_hgl6U6ZqOb8EM_L8DX3Lp5FhIVTQ%3D
  workspaces:
  - name: source-code
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  taskRunSpecs:
  - pipelineTaskName: build
    serviceAccountName: builder
  #   computeResources:
  #     requests:
  #       cpu: 1
  # - pipelineTaskName: notify
  #   serviceAccountName: notifier
