apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: clone-kaniko-build-push
spec:
  description: |
    This pipeline clones a git repo, builds a Docker image with Kaniko and
    pushes it to Google Artifact repository.
  workspaces:
  - name: source-code
  params:
  - name: image
  - name: repo-url
  # - name: chat-webhook-url
  results:
  - name: image-digest
    value: $(tasks.build.results.digest)
  tasks:
  - name: fetch-source
    taskRef:
      resolver: hub
      params:
      - name: kind
        value: task
      - name: name
        value: git-clone
      - name: version
        value: "0.7"
    workspaces:
    - name: output
      workspace: source-code
    params:
    - name: url
      value: $(params.repo-url)
  - name: build
    taskRef:
      name: kaniko-build
    params:
    - name: image
      value: $(params.image)
    workspaces:
    - name: source-code
    runAfter:
    - fetch-source
  # finally:
  # - name: notify
  #   taskRef:
  #     name: notify-google-chat
  #   params:
  #   - name: webhook-url
  #     value: $(params.chat-webhook-url)
  #   - name: message
  #     value: "Build status: $(tasks.build.status)"
