apiVersion: v1
kind: ServiceAccount
metadata:
  name: container-registry-sa
  annotations:
    iam.gke.io/gcp-service-account: leebernick-container-registry@tekton-interns.iam.gserviceaccount.com
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
spec:
  triggers:
    - name: github-listener
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["check_suite"]
        - name: "only when a new check suite is requested"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.action in ['requested']"
      bindings:
        - ref: github-check-binding
      template:
        ref: github-template
  resources:
    kubernetesResource:
      serviceType: LoadBalancer
      spec:
        template:
          spec:
            serviceAccountName: dogfood-sa
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-check-binding
spec:
  params:
    - name: revision
      value: $(body.check_suite.head_sha)
    - name: repo-full-name
      value: $(body.repository.full_name)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-template
spec:
  params:
    - name: repo-full-name
    - name: revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: github-run-
      spec:
        pipelineRef:
          name: ci-pipeline
        serviceAccountName: container-registry-sa
        params:
        - name: repo-full-name
          value: $(tt.params.repo-full-name)
        - name: revision
          value: $(tt.params.revision)
        - name: github-app-id
          value: "229835"
        - name: app-installation-id
          value: "28405964"
        workspaces:
        - name: github-app-private-key
          secret:
            secretName: github-app-key
        - name: source
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
          